version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: test_task_alma_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8010:8000
    depends_on:
      - redis

  redis:
    image: redis:6-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: test_task_alma_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: test_task_alma_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: test_task_alma_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    ports:
      - 5557:5555
    depends_on:
      - redis


#version: "3.7"
#
#volumes:
#  static_volume:
#
#services:
#  nginx:
#    build:
#      context: ./compose/local/nginx
#      dockerfile: ./Dockerfile
#    volumes:
#      - static_volume:/app/staticfiles
#    ports:
#      - 8000:80
#    depends_on:
#      - django
#
#  django: &django
#    build:
#      context: .
#      dockerfile: ./compose/local/django/Dockerfile
#    command: gunicorn test_task_alma.wsgi:application -b 0.0.0.0:8000 --reload
#    volumes:
#      - static_volume:/app/staticfiles
#    expose:
#      - 8000
#
#
#  redis:
#    image: "redis:alpine"
#
#  celeryworker:
#    build:
#      context: .
#      dockerfile: ./compose/local/django/Dockerfile
#    container_name: celeryworker
#    depends_on:
#      - redis
#    command: /start-celeryworker
#
#  celerybeat:
#    build:
#      context: .
#      dockerfile: ./compose/local/django/Dockerfile
#    container_name: celerybeat
#    depends_on:
#      - redis
#    command: /start-celerybeat
#
