# Generated by Django 4.0 on 2021-12-19 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KernelTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Дата запуска расчета')),
                ('task_id', models.CharField(max_length=255, verbose_name='Идентификатор задачи')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('lead_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время выполнения задачи')),
            ],
            options={
                'verbose_name': 'Задача расчета',
                'verbose_name_plural': 'Задачи расчетов',
            },
        ),
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата генерации расчета')),
                ('liquid', models.FloatField(verbose_name='Жидкость')),
                ('oil', models.FloatField(verbose_name='Нефть')),
                ('water', models.FloatField(verbose_name='Вода')),
                ('wct', models.FloatField(verbose_name='Обводненность')),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.kerneltasks', verbose_name='Задача расчета')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
            },
        ),
    ]
